name: Run Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install

    - name: Install Playwright dependencies
      run: |
        npx playwright install --with-deps 

    - name: Run Playwright tests
      run: |
        npx playwright test --reporter=html

    - name: Upload test results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: playwright-test-results
        path: test-results/
