name: Run Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Show Node.js version
      run: |
        node -v

    - name: Install dependencies
      run: |
        npm install

    - name: Install Playwright dependencies
      run: |
        sudo npm install playwright --unsafe-perm=true --allow-root

    - name: Install Playwright globally
      run: |
        sudo npm install -g playwright

    - name: Show Playwright version
      run: |
        npx playwright --version

    - name: Fix Playwright permissions
      run: |
        sudo chmod -R 777 node_modules
        sudo chmod -R +x node_modules/playwright

    - name: Run Playwright tests
      run: |
        npx playwright test --reporter=html

    - name: Upload test results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: playwright-test-results
        path: test-results/
