name: Run Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: |
        sudo npm install

    - name: Install Playwright dependencies
      run: |
        sudo npm install playwright --unsafe-perm=true --allow-root

    - name: Fix permissions for node_modules
      run: |
        sudo chmod -R 777 node_modules

    - name: Install Playwright Browsers
      run: |
        sudo npx playwright install

    - name: Run Playwright tests
      run: |
        sudo npx playwright test --reporter=html

    - name: Upload Playwright HTML report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: playwright-report


    - name: Collect test errors
      run: |
        cat playwright-report/index.html | grep -i "error" > errors.txt


    - name: Upload errors.txt if errors exist
      if: success() && fileExists('errors.txt')
      uses: actions/upload-artifact@v3
      with:
        name: test-errors
        path: errors.txt